//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sweph.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sweph.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: not found.
        /// </summary>
        internal static string Asteroid_NameNotFound {
            get {
                return ResourceManager.GetString("Asteroid_NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find a constructor for type &apos;{0}&apos;.
        /// </summary>
        internal static string Dependency_Error_CantFindConstructor {
            get {
                return ResourceManager.GetString("Dependency_Error_CantFindConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can&apos;t be instanciate.
        /// </summary>
        internal static string Dependency_Error_CantInstanciateType {
            get {
                return ResourceManager.GetString("Dependency_Error_CantInstanciateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resolve parameter &apos;{0}&apos; of type &apos;{1}&apos; for construct &apos;{2}&apos;.
        /// </summary>
        internal static string Dependency_Error_CantResolveParameterForConstruct {
            get {
                return ResourceManager.GetString("Dependency_Error_CantResolveParameterForConstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resolve type &apos;{0}&apos;.
        /// </summary>
        internal static string Dependency_Error_CantResolveType {
            get {
                return ResourceManager.GetString("Dependency_Error_CantResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in file {0}, line {1}: {2}.
        /// </summary>
        internal static string Error_ReadingFile {
            get {
                return ResourceManager.GetString("Error_ReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eccentricity invalid (no parabolic or hyperbolic orbits allowed).
        /// </summary>
        internal static string Fictitious_ErrorEccentricityValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorEccentricityValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elements for planet {1} not found.
        /// </summary>
        internal static string Fictitious_ErrorElementsNotFound {
            get {
                return ResourceManager.GetString("Fictitious_ErrorElementsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inclination value invalid.
        /// </summary>
        internal static string Fictitious_ErrorInclinationValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorInclinationValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid epoch.
        /// </summary>
        internal static string Fictitious_ErrorInvalidEpoch {
            get {
                return ResourceManager.GetString("Fictitious_ErrorInvalidEpoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid equinox.
        /// </summary>
        internal static string Fictitious_ErrorInvalidEquinox {
            get {
                return ResourceManager.GetString("Fictitious_ErrorInvalidEquinox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mean anomaly value invalid.
        /// </summary>
        internal static string Fictitious_ErrorMeanAnomalyValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorMeanAnomalyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nine elements required.
        /// </summary>
        internal static string Fictitious_ErrorNineElementsRequired {
            get {
                return ResourceManager.GetString("Fictitious_ErrorNineElementsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node value invalid.
        /// </summary>
        internal static string Fictitious_ErrorNodeValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorNodeValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error no elements for fictitious body no {0}.
        /// </summary>
        internal static string Fictitious_ErrorNoElements {
            get {
                return ResourceManager.GetString("Fictitious_ErrorNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to perihelion argument value invalid.
        /// </summary>
        internal static string Fictitious_ErrorPerihelionArgumentValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorPerihelionArgumentValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semi-axis value invalid.
        /// </summary>
        internal static string Fictitious_ErrorSemiAxisValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorSemiAxisValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not found.
        /// </summary>
        internal static string Fictitious_NameNotFound {
            get {
                return ResourceManager.GetString("Fictitious_NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adams.
        /// </summary>
        internal static string FictitiousName_Adams {
            get {
                return ResourceManager.GetString("FictitiousName_Adams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admetos.
        /// </summary>
        internal static string FictitiousName_Admetos {
            get {
                return ResourceManager.GetString("FictitiousName_Admetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollon.
        /// </summary>
        internal static string FictitiousName_Apollon {
            get {
                return ResourceManager.GetString("FictitiousName_Apollon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupido.
        /// </summary>
        internal static string FictitiousName_Cupido {
            get {
                return ResourceManager.GetString("FictitiousName_Cupido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hades.
        /// </summary>
        internal static string FictitiousName_Hades {
            get {
                return ResourceManager.GetString("FictitiousName_Hades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harrington.
        /// </summary>
        internal static string FictitiousName_Harrington {
            get {
                return ResourceManager.GetString("FictitiousName_Harrington", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isis-Transpluto.
        /// </summary>
        internal static string FictitiousName_IsisTranspluto {
            get {
                return ResourceManager.GetString("FictitiousName_IsisTranspluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kronos.
        /// </summary>
        internal static string FictitiousName_Kronos {
            get {
                return ResourceManager.GetString("FictitiousName_Kronos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverrier.
        /// </summary>
        internal static string FictitiousName_Leverrier {
            get {
                return ResourceManager.GetString("FictitiousName_Leverrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowell.
        /// </summary>
        internal static string FictitiousName_Lowell {
            get {
                return ResourceManager.GetString("FictitiousName_Lowell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nibiru.
        /// </summary>
        internal static string FictitiousName_Nibiru {
            get {
                return ResourceManager.GetString("FictitiousName_Nibiru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickering.
        /// </summary>
        internal static string FictitiousName_Pickering {
            get {
                return ResourceManager.GetString("FictitiousName_Pickering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poseidon.
        /// </summary>
        internal static string FictitiousName_Poseidon {
            get {
                return ResourceManager.GetString("FictitiousName_Poseidon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulkanus.
        /// </summary>
        internal static string FictitiousName_Vulkanus {
            get {
                return ResourceManager.GetString("FictitiousName_Vulkanus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus.
        /// </summary>
        internal static string FictitiousName_Zeus {
            get {
                return ResourceManager.GetString("FictitiousName_Zeus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not found.
        /// </summary>
        internal static string Planet_NameNotFound {
            get {
                return ResourceManager.GetString("Planet_NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceres.
        /// </summary>
        internal static string PlanetName_Ceres {
            get {
                return ResourceManager.GetString("PlanetName_Ceres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiron.
        /// </summary>
        internal static string PlanetName_Chiron {
            get {
                return ResourceManager.GetString("PlanetName_Chiron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        internal static string PlanetName_Earth {
            get {
                return ResourceManager.GetString("PlanetName_Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intp. Apogee.
        /// </summary>
        internal static string PlanetName_IntpApogee {
            get {
                return ResourceManager.GetString("PlanetName_IntpApogee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intp. Perigee.
        /// </summary>
        internal static string PlanetName_IntpPerigee {
            get {
                return ResourceManager.GetString("PlanetName_IntpPerigee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juno.
        /// </summary>
        internal static string PlanetName_Juno {
            get {
                return ResourceManager.GetString("PlanetName_Juno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jupiter.
        /// </summary>
        internal static string PlanetName_Jupiter {
            get {
                return ResourceManager.GetString("PlanetName_Jupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mars.
        /// </summary>
        internal static string PlanetName_Mars {
            get {
                return ResourceManager.GetString("PlanetName_Mars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mean Apogee.
        /// </summary>
        internal static string PlanetName_MeanApogee {
            get {
                return ResourceManager.GetString("PlanetName_MeanApogee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mean Node.
        /// </summary>
        internal static string PlanetName_MeanNode {
            get {
                return ResourceManager.GetString("PlanetName_MeanNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercury.
        /// </summary>
        internal static string PlanetName_Mercury {
            get {
                return ResourceManager.GetString("PlanetName_Mercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon.
        /// </summary>
        internal static string PlanetName_Moon {
            get {
                return ResourceManager.GetString("PlanetName_Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neptune.
        /// </summary>
        internal static string PlanetName_Neptune {
            get {
                return ResourceManager.GetString("PlanetName_Neptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osc. Apogee.
        /// </summary>
        internal static string PlanetName_OscuApogee {
            get {
                return ResourceManager.GetString("PlanetName_OscuApogee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallas.
        /// </summary>
        internal static string PlanetName_Pallas {
            get {
                return ResourceManager.GetString("PlanetName_Pallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pholus.
        /// </summary>
        internal static string PlanetName_Pholus {
            get {
                return ResourceManager.GetString("PlanetName_Pholus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pluto.
        /// </summary>
        internal static string PlanetName_Pluto {
            get {
                return ResourceManager.GetString("PlanetName_Pluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturn.
        /// </summary>
        internal static string PlanetName_Saturn {
            get {
                return ResourceManager.GetString("PlanetName_Saturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string PlanetName_Sun {
            get {
                return ResourceManager.GetString("PlanetName_Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true Node.
        /// </summary>
        internal static string PlanetName_TrueNode {
            get {
                return ResourceManager.GetString("PlanetName_TrueNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uranus.
        /// </summary>
        internal static string PlanetName_Uranus {
            get {
                return ResourceManager.GetString("PlanetName_Uranus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venus.
        /// </summary>
        internal static string PlanetName_Venus {
            get {
                return ResourceManager.GetString("PlanetName_Venus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vesta.
        /// </summary>
        internal static string PlanetName_Vesta {
            get {
                return ResourceManager.GetString("PlanetName_Vesta", resourceCulture);
            }
        }
    }
}
